service: default
runtime: go
api_version: go1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
  mime_type: image/x-icon
  secure: always
- url: /manifest.json
  static_files: md/manifest.json
  upload: md/manifest.json
  mime_type: application/json; charset=UTF-8
  secure: always
- url: /service.js
  static_files: workers/service.js
  upload: workers/service.js
  mime_type: application/javascript; charset=UTF-8
  secure: always
- url: /scripts
  static_dir: scripts
  mime_type: application/javascript; charset=UTF-8
  secure: always
- url: /(.*\.png)
  static_files: img/\1
  upload: img/(.*\.png)
  mime_type: image/png
  secure: always
- url: /(.*\.svg)
  static_files: img/\1
  upload: img/(.*\.svg)
  mime_type: image/svg+xml
  secure: always
- url: /.*
  script: _go_app
  secure: always
- url: /
  script: _go_app
  secure: always

skip_files:
- ^(.*/)?\.DS_Store$
- ^(.*/)?.*\.yaml$
- scripts/tsconfig.json
- workers/tsconfig.json
- README.md

# - url: /(.*\.map)
#   static_files: ./\1
#   upload: /(.*\.map)
#   mime_type: application/javascript; charset=UTF-8

# secure: always
# login: admin
# http_headers:
#   Content-Type: text/html; charset=UTF-8
#   Access-Control-Allow-Origin: https://accounts.google.com
