.PHONY: test install

test:
	go test -v
# go test -run=Time/12:[0-9] -v

install:
	go get -u github.com/gertcuykens/mollie-api-go
	go get -u github.com/gertcuykens/httx
	go get -u google.golang.org/appengine
